var langGl = {
    ru: {
        ogTitle: 'Логическая игра ЧИСЛА',
        header: '<span>ЧИСЛА</span> логическая игра',
        hi: 'Приветствую',
        target: 'Задача отгадать загаданные прогаммой числа с соблюдением точной последовательности.',
        targetAgain: 'Задача все та же - отгадать загаданные прогаммой числа с соблюдением точной последовательности.',
        bestResult: 'Ваш лучший результат',
        bestResult2: 'Лучший результат',
        typeName: 'Введите ваше имя',
        level: 'Уровень сложности',
        startBtn: 'Начать игру',
        delUser: 'Удалить пользователя',
        tEr: 'Поле "Имя" не должно быть пустым!',
        dUser: 'При удалении пользователя будет удалена вся история. Удалить пользователя?',
        tSu: 'Поздравляем! Это ваш лучший результат',
        tCongr: 'Поздравлю, Вы победили!',
        ugadano: 'Угадано чисел',
        nameste: 'На месте',
        startAgain: 'Начать заново',
        cancelBtn: 'Отмена',
        confirmBtn: 'Да'

    },
    uk: {
        ogTitle: 'Логічна гра ЧИСЛА',
        header: '<span>ЧИСЛА</span> логічна гра',
        hi: 'Вітаю',
        target: 'Завдання відгадати загадані прогамма числа з дотриманням точної послідовності.',
        targetAgain: 'Завдання все та ж - відгадати загадані прогамма числа з дотриманням точної послідовності.',
        bestResult: 'Ваш найкращий результат',
        bestResult2: 'Найкращий результат',
        typeName: 'Введіть ваше ім\'я',
        level: 'Рівень важкості',
        startBtn: 'Почати гру',
        delUser: 'Видалити користувача',
        tEr: 'Поле "Ім\'я" не повинно бути пустим!',
        dUser: 'При видаленні користувача буде видалена вся історія. Видалити користувача?',
        tSu: 'Вітаю! Це ваш кращій результат',
        tCongr: 'Поздоровлю, Ви перемогли!',
        ugadano: 'Відгадано чисел',
        nameste: 'На місці',
        startAgain: 'Почати спочатку',
        cancelBtn: 'Відмінити',
        confirmBtn: 'Да'
    },
    en: {
        ogTitle: 'Logic game NUMBERS',
        header: '<span>NUMBERS</span> logic game',
        hi: 'Hi',
        target: 'The task is to guess the programmed numbers with the exact sequence.',
        targetAgain: 'The task is still the same - guess the programmed numbers with the exact sequence.',
        bestResult: 'Your best result',
        bestResult2: 'Best result',
        typeName: 'Enter your name',
        level: 'Difficulty level',
        startBtn: 'Start game',
        delUser: 'Remove user',
        tEr: 'The "Name" field can not be empty!',
        dUser: 'If you delete the user, the entire history will be deleted. Delete user?',
        tSu: 'Congratulations! This is your best result',
        tCongr: 'Congratulations, you won!',
        ugadano: 'Guessed numbers',
        nameste: 'On-site',
        startAgain: 'Start again',
        cancelBtn: 'Cancel',
        confirmBtn: 'Yes'
    }
};